export const PRODUCTS_DATA = {
  morning: {
    slug: 'morning',
    phase: '01',
    title: 'Morning Pack',
    tagline: 'Activate.',
    accentColor: '#8B0015',
    accentLight: '#FFF0F0',
    image: '/Morning2.png',
    shortDesc: 'Precision-dosed micronutrients that prime your biology from the first hour of the day.',
    longDesc: 'The Morning Pack is engineered to synchronize with your circadian rhythm — the 24-hour biological clock that governs cortisol, testosterone, and cellular metabolism. Taken within 30 minutes of waking, it activates the enzymatic pathways responsible for energy production, immune defense, and cognitive sharpness. Every compound is selected for its synergistic role in the morning hormonal environment.',
    ingredients: [
      {
        name: 'Vitamin A',
        form: 'Retinyl Palmitate (CWD)',
        dose: '800 µg',
        image: '/ingrediente/vitamin-a.png',
        what: 'Immune Architecture & Cellular Growth',
        why: 'Vitamin A regulates the expression of over 500 genes involved in immune function, cellular differentiation, and tissue integrity. In athletes, it supports the repair of epithelial barriers damaged by intense effort and plays a direct role in glycoprotein synthesis — essential for joint lubrication and mucosal defense against pathogens.',
      },
      {
        name: 'Vitamin C',
        form: 'Calcium Ascorbate',
        dose: '200 mg',
        image: '/ingrediente/vitamin-c.png',
        what: 'Antioxidant Defense & Collagen Synthesis',
        why: 'Intense exercise generates reactive oxygen species that damage cell membranes and mitochondrial DNA. Vitamin C in calcium ascorbate form provides superior bioavailability and gastric tolerance. It is the rate-limiting step in collagen synthesis — the structural protein of tendons, ligaments, and cartilage — making it non-negotiable for athletes who train daily.',
      },
      {
        name: 'Vitamin D3',
        form: 'Cholecalciferol (Vegan)',
        dose: '25 µg',
        image: '/ingrediente/vitamin-d3.png',
        what: 'Hormonal Regulation & Immune Command',
        why: 'Over 2,000 genes contain vitamin D response elements. In athletes, D3 directly stimulates testosterone production in Leydig cells, regulates calcium for bone density, and orchestrates the innate immune response. Studies show that 70–80% of indoor-training athletes are deficient, correlating with increased injury rates, fatigue, and suppressed immunity.',
      },
      {
        name: 'Vitamin E',
        form: 'd-alpha-Tocopheryl',
        dose: '12 mg',
        image: '/ingrediente/vitamin-e.png',
        what: 'Membrane Protection & Cardiovascular Defense',
        why: 'The only fat-soluble antioxidant integrated directly into cell membranes, vitamin E intercepts lipid peroxidation chain reactions before they propagate. It works in a synergistic cycle with vitamin C — when vitamin E is oxidized neutralizing a free radical, vitamin C regenerates it. Critical for protecting the mitochondrial inner membrane during aerobic metabolism.',
      },
      {
        name: 'Vitamin K2',
        form: 'Menaquinone-7 (MK-7)',
        dose: '50 µg',
        image: '/ingrediente/vitamin-k2.png',
        what: 'Calcium Trafficking & Vascular Protection',
        why: 'MK-7 is the long-chain form of K2 with a 72-hour half-life, ensuring continuous activation of osteocalcin and matrix Gla protein. These proteins direct calcium to bones — where it belongs — and prevent its deposition in arterial walls and soft tissue. Essential when supplementing D3, which significantly increases calcium absorption.',
      },
      {
        name: 'Vitamin B12',
        form: 'Methylcobalamin',
        dose: '100 µg',
        image: '/ingrediente/vitamin-b12.png',
        what: 'Neurological Function & Red Blood Cell Production',
        why: 'The methylated form bypasses the MTHFR conversion step, providing immediate bioavailability regardless of genetic variants. B12 is essential for the synthesis of myelin — the nerve insulation that governs motor speed and proprioception — and for red blood cell maturation, directly impacting oxygen transport capacity and endurance performance.',
      },
      {
        name: 'B Complex',
        form: 'Methylated B-Complex Premix',
        dose: '100% RDA',
        image: '/ingrediente/vitamin-b-complex.png',
        what: 'Energy Metabolism & Neurotransmitter Synthesis',
        why: 'The B-vitamin family functions as enzymatic cofactors in the Krebs cycle, electron transport chain, and fatty acid oxidation — the three pillars of cellular energy production. The methylated forms bypass common genetic bottlenecks. B6 specifically controls serotonin and dopamine synthesis, directly influencing motivation, mood, and pain tolerance during training.',
      },
      {
        name: 'Zinc',
        form: 'Zinc Bisglycinate',
        dose: '10 mg',
        image: '/ingrediente/zinc.png',
        what: 'Testosterone Synthesis & Immune Signaling',
        why: 'Zinc is the most abundant intracellular transition metal, serving as a structural component in over 300 enzymes and 2,000 transcription factors. For athletes, its most critical roles are in testosterone biosynthesis and the activity of T-lymphocytes. Sweat losses of 1–2 mg per hour mean intense daily training can rapidly deplete stores, collapsing hormonal output.',
      },
      {
        name: 'Copper',
        form: 'Copper Bisglycinate',
        dose: '0.5 mg',
        image: '/ingrediente/copper.png',
        what: 'Antioxidant Enzyme Support & Connective Tissue',
        why: 'Copper is the essential cofactor in superoxide dismutase (Cu/Zn-SOD), the primary antioxidant enzyme in the cytoplasm. It is also required for cross-linking collagen and elastin fibers in connective tissue. Copper and zinc must be supplemented in the correct ratio — supplementing zinc alone without copper creates a functional copper deficiency over time.',
      },
      {
        name: 'Magnesium',
        form: 'Magnesium Citrate',
        dose: '350 mg',
        image: '/ingrediente/magnesium.png',
        what: 'ATP Production & Muscle Function',
        why: 'Magnesium is a cofactor in over 300 enzymatic reactions, including every step of ATP synthesis. Without sufficient intracellular magnesium, energy production stalls. Citrate form is selected for its superior absorption and gentle gastrointestinal profile. Athletes lose up to 20% more magnesium through sweat than sedentary individuals, making deficiency the most common performance-limiting micronutrient deficit.',
      },
      {
        name: 'Selenium',
        form: 'Selenomethionine',
        dose: '50 µg',
        image: '/ingrediente/selenium.png',
        what: 'Glutathione Activation & Thyroid Regulation',
        why: 'Selenium is the essential cofactor in glutathione peroxidase — the body\'s master antioxidant system that neutralizes hydrogen peroxide produced during mitochondrial respiration. It is also required for the conversion of T4 to the active T3 thyroid hormone, regulating metabolic rate, body composition, and recovery speed. Selenomethionine provides 90% bioavailability versus 50% for inorganic forms.',
      },
    ],
  },

  recovery: {
    slug: 'recovery',
    phase: '04',
    title: 'Recovery Pack',
    tagline: 'Rebuild.',
    accentColor: '#E8631A',
    accentLight: '#FFF3EC',
    image: '/Recovery2.png',
    shortDesc: 'Master recovery formula. Glycogen reload, anabolic defense, and neuromuscular repair in one 38g serving.',
    longDesc: 'The Recovery Pack is formulated around the 45-minute anabolic window — the period immediately post-exercise when muscle cells are hypersensitive to nutrients. It simultaneously addresses the four pillars of recovery: glycogen resynthesis, muscle protein synthesis, anti-inflammatory response, and nervous system downregulation. Every ingredient is included at the dose where clinical data shows meaningful effect.',
    ingredients: [
      {
        name: 'Maltodextrin (Low DE)',
        form: 'Carbohydrate Matrix',
        dose: '20 000 mg',
        image: '/ingrediente/maltodextrin.jpeg',
        what: 'Glycogen Resynthesis & Insulin Spike',
        why: 'Low dextrose equivalent maltodextrin provides a moderate glycemic response — high enough to trigger the insulin spike required to drive amino acids into muscle cells, but controlled enough to avoid reactive hypoglycemia. 20g of carbohydrates initiates glycogen resynthesis at the maximum enzymatic rate of glycogen synthase, replenishing muscle fuel stores within 60–90 minutes post-exercise.',
      },
      {
        name: 'EAA Complex',
        form: 'Full Spectrum (all 9 EAAs)',
        dose: '7 000 mg',
        image: '/ingrediente/eaa.jpeg',
        what: 'Immediate Muscle Protein Synthesis',
        why: 'Essential amino acids cannot be synthesized by the body and must be consumed. Unlike whole protein sources that require digestion, free-form EAAs are absorbed directly into the bloodstream within 15–30 minutes, bypassing the liver and reaching muscle tissue immediately. The leucine content within this complex activates the mTOR pathway — the molecular switch that initiates muscle protein synthesis.',
      },
      {
        name: 'Creatine Monohydrate',
        form: 'Micronized (Clinical Grade)',
        dose: '5 000 mg',
        image: '/ingrediente/creatine.jpeg',
        what: 'ATP Replenishment & Cell Volumization',
        why: 'The most researched sports supplement in existence with over 500 peer-reviewed studies. Post-workout is the optimal timing for creatine — when muscle cells are most permeable and insulin is elevated, maximizing uptake without requiring a separate loading protocol. 5g replenishes phosphocreatine stores depleted during high-intensity effort, accelerating readiness for the next session.',
      },
      {
        name: 'L-Glutamine',
        form: 'Free-Form L-Glutamine',
        dose: '3 000 mg',
        image: '/ingrediente/l-glutamine.jpeg',
        what: 'Gut Barrier Integrity & Immune Support',
        why: 'Intense exercise can deplete plasma glutamine by up to 45%, and intestinal enterocytes depend on glutamine as their primary fuel source. When depleted, the tight junctions of the gut barrier become permeable — allowing bacterial endotoxins to enter the bloodstream, triggering systemic inflammation and suppressing immune function. 3g restores intestinal integrity and supports lymphocyte proliferation.',
      },
      {
        name: 'HMB (Calcium Salt)',
        form: 'Beta-Hydroxy Beta-Methylbutyrate',
        dose: '1 500 mg',
        image: '/ingrediente/hmb.jpeg',
        what: 'Anabolic Shield & Catabolism Prevention',
        why: 'HMB is a leucine metabolite that activates mTOR while simultaneously inhibiting the ubiquitin-proteasome pathway — the primary mechanism of muscle protein degradation. Studies show 1.5g post-workout significantly reduces creatine kinase and LDH levels (markers of muscle damage) and preserves lean mass during caloric deficit. Calcium salt form provides superior stability and absorption.',
      },
      {
        name: 'Tart Cherry Extract',
        form: 'Standardized Anthocyanin Extract',
        dose: '500 mg',
        image: '/ingrediente/tart-cherry.jpeg',
        what: 'Natural Anti-Inflammatory & DOMS Reduction',
        why: 'Tart cherry\'s anthocyanins inhibit COX-1 and COX-2 enzymes — the same targets as NSAIDs like ibuprofen — without gastrointestinal side effects or interference with training adaptation. Multiple RCTs demonstrate significant reduction in delayed onset muscle soreness (DOMS) at this dose, allowing athletes to train with greater frequency and output. Also supports overnight sleep quality through melatonin precursor content.',
      },
      {
        name: 'Himalayan Pink Salt',
        form: '84 Trace Minerals',
        dose: '300 mg',
        image: '/ingrediente/himalayan-salt.jpeg',
        what: 'Electrolyte Restoration & Glucose Co-Transport',
        why: 'Sodium is the primary cation lost through sweat — up to 1,400mg per hour in high-intensity exercise. Restoring sodium post-workout reactivates the sodium-glucose cotransporter (SGLT1) that is required to absorb glucose into muscle cells. Himalayan salt\'s broad mineral profile also replaces potassium, magnesium, calcium, and trace elements lost through perspiration.',
      },
      {
        name: 'Magnesium Bisglycinate',
        form: 'Chelated Magnesium',
        dose: '150 mg',
        image: '/ingrediente/magnesium-bisglycinate.jpeg',
        what: 'Neuromuscular Relaxation & Cortisol Modulation',
        why: 'Post-exercise, elevated cortisol and epinephrine maintain the sympathetic nervous system in a state of heightened arousal, counteracting recovery. Magnesium glycinate is the most bioavailable form, with glycine providing additional inhibitory neurotransmitter activity. Together, they accelerate the shift from sympathetic to parasympathetic dominance, reducing muscle tension, heart rate, and cortisol — the prerequisites for anabolic recovery.',
      },
      {
        name: 'L-Theanine',
        form: 'Free-Form L-Theanine',
        dose: '100 mg',
        image: '/ingrediente/l-theanine-recovery.jpeg',
        what: 'CNS Downregulation & Alpha Wave Induction',
        why: 'L-Theanine is a non-protein amino acid found in green tea that promotes alpha brain wave activity — the cognitive state associated with relaxed alertness and accelerated learning. Post-workout, it counteracts the stimulatory effects of residual catecholamines, facilitating the parasympathetic switch required for anabolic processes. Critically, it achieves this without sedation, preserving cognitive function during the recovery window.',
      },
      {
        name: 'AstraGin®',
        form: 'Astragalus + Panax Notoginseng',
        dose: '50 mg',
        image: '/ingrediente/astragin.png',
        what: 'Absorption Amplifier',
        why: 'AstraGin is a patented compound that upregulates the transporter proteins (SGLT1, CAT1, PEPT1) responsible for nutrient absorption in the small intestine. Clinical studies show it increases amino acid absorption by up to 62%, creatine uptake by 33%, and glucose transport by 55%. A small dose of 50mg amplifies the bioavailability of every other ingredient in the formula.',
      },
    ],
  },
};
